---
- name: Testing andrewrothstein.stepca
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'step-ca --version'
      ansible.builtin.command: step-ca --version
      changed_when: false
      register: stepca_output
    - name: Output from 'step-ca --version'
      ansible.builtin.debug:
        msg: '{{ stepca_output.stdout }}'
