---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: check for install at {{ stepca_install_bin_dir }}
  become: true
  stat:
    path: '{{ stepca_install_bin_dir }}'
  changed_when: false
  register: stepca_binary
- when: not stepca_binary.stat.exists
  block:
    - name: downloading {{ stepca_url }} to {{ stepca_tmp_archive }}
      become: true
      become_user: root
      get_url:
        url: '{{ stepca_url }}'
        dest: '{{ stepca_tmp_archive }}'
        mode: 0644
        checksum: '{{ stepca_checksum }}'
    - name: unarchive {{ stepca_tmp_archive }} to {{ stepca_parent_install_dir }}
      become: true
      become_user: root
      unarchive:
        remote_src: true
        src: '{{ stepca_tmp_archive }}'
        dest: '{{ stepca_parent_install_dir }}'
        creates: '{{ stepca_install_bin_dir }}'
  always:
    - name: rm {{ stepca_tmp_archive }}
      become: true
      become_user: root
      file:
        path: '{{ stepca_tmp_archive }}'
        state: absent
- name: linking executables
  become: true
  become_user: root
  with_items: '{{ stepca_exes }}'
  file:
    src: '{{ stepca_install_bin_dir }}/{{ item }}'
    dest: '{{ stepca_parent_install_dir }}/bin/{{ item }}'
    state: link
