---
- name: Resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Check for install at {{ stepca_install_dir }}
  become: true
  ansible.builtin.stat:
    path: '{{ stepca_install_exe }}'
  changed_when: false
  register: stepca_binary
- name: Downloading and installing step-ca
  when: not stepca_binary.stat.exists
  block:
    - name: Downloading {{ stepca_url }} to {{ stepca_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ stepca_url }}'
        dest: '{{ stepca_tmp_archive }}'
        mode: '644'
        checksum: '{{ stepca_checksum }}'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Mkdir {{ stepca_install_dir }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ stepca_install_dir }}'
        state: directory
        mode: '755'
    - name: Unarchive {{ stepca_tmp_archive }} to {{ stepca_install_dir }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ stepca_tmp_archive }}'
        dest: '{{ stepca_install_dir }}'
        creates: '{{ stepca_install_exe }}'
  always:
    - name: Rm {{ stepca_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ stepca_tmp_archive }}'
        state: absent
- name: Linking executables
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ stepca_install_exe }}'
    dest: '{{ stepca_link }}'
    state: link
